### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by lamoboos223** [lamoboos223/Restaurant-System#1]
in this project we will create a spring boot app that connects to a kafka broker and send the client order data as avro.

we need to install the following, zookeeper, kafka, schema registry and postgres database.

**Comment by begemot63** [comment]
How this design guarantee the order of coming events?   Order Shipped event can be handled and persisted in DB before the order is approved

**Comment by lamoboos223** [comment]
Hi @begemot63 
So in this project we just wanted to show you a tutorial how it’s done with the help of the kafka. We didn’t actually work so well on the requirement, but the project now serve its purpose as a getting started.

**Comment by lamoboos223** [comment]
Also these events that describes the states of the order is saved in queue (kafka) at the final stage it will be persisted in the DB.
